import { User, Competition, Team, Match, Bolao, Prize, Tenant } from "@/types";

export const mockCompetitions: Competition[] = [
  {
    id: "comp-1",
    name: "Brasileirão Série A",
    slug: "brasileirao-serie-a",
    country: "Brasil",
    logoUrl: null,
    season: "2024",
    isActive: true,
  },
  {
    id: "comp-2",
    name: "Champions League",
    slug: "champions-league",
    country: "Europa",
    logoUrl: null,
    season: "2024/25",
    isActive: true,
  },
  {
    id: "comp-3",
    name: "Copa Libertadores",
    slug: "libertadores",
    country: "América do Sul",
    logoUrl: null,
    season: "2024",
    isActive: true,
  },
  {
    id: "comp-4",
    name: "Premier League",
    slug: "premier-league",
    country: "Inglaterra",
    logoUrl: null,
    season: "2024/25",
    isActive: true,
  },
];

export const mockTeams: Team[] = [
  { id: "team-1", name: "Flamengo", shortName: "FLA", country: "Brasil", competitionId: "comp-1" },
  { id: "team-2", name: "Corinthians", shortName: "COR", country: "Brasil", competitionId: "comp-1" },
  { id: "team-3", name: "Palmeiras", shortName: "PAL", country: "Brasil", competitionId: "comp-1" },
  { id: "team-4", name: "Santos", shortName: "SAN", country: "Brasil", competitionId: "comp-1" },
  { id: "team-5", name: "Grêmio", shortName: "GRE", country: "Brasil", competitionId: "comp-1" },
  { id: "team-6", name: "Atlético Mineiro", shortName: "ATM", country: "Brasil", competitionId: "comp-1" },
  { id: "team-7", name: "Manchester City", shortName: "MCI", country: "Inglaterra", competitionId: "comp-2" },
  { id: "team-8", name: "Real Madrid", shortName: "RMA", country: "Espanha", competitionId: "comp-2" },
  { id: "team-9", name: "Barcelona", shortName: "BAR", country: "Espanha", competitionId: "comp-2" },
  { id: "team-10", name: "PSG", shortName: "PSG", country: "França", competitionId: "comp-2" },
];

const now = new Date();
const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
const dayAfter = new Date(now.getTime() + 48 * 60 * 60 * 1000);
const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);

export const mockMatches: Match[] = [
  {
    id: "match-1",
    homeTeamId: "team-1",
    awayTeamId: "team-2",
    competitionId: "comp-1",
    scheduledAt: new Date(now.getTime() + 2 * 60 * 60 * 1000),
    closedAt: new Date(now.getTime() + 90 * 60 * 1000),
    status: "SCHEDULED",
    venue: "Estádio Maracanã",
    pointsMultiplier: 1.0,
    createdAt: now,
    homeTeam: mockTeams[0],
    awayTeam: mockTeams[1],
    competition: mockCompetitions[0],
  },
  {
    id: "match-2",
    homeTeamId: "team-7",
    awayTeamId: "team-8",
    competitionId: "comp-2",
    scheduledAt: new Date(now.getTime() + 4 * 60 * 60 * 1000),
    closedAt: new Date(now.getTime() + 3.5 * 60 * 60 * 1000),
    status: "SCHEDULED",
    venue: "Etihad Stadium",
    pointsMultiplier: 1.5,
    createdAt: now,
    homeTeam: mockTeams[6],
    awayTeam: mockTeams[7],
    competition: mockCompetitions[1],
  },
  {
    id: "match-3",
    homeTeamId: "team-3",
    awayTeamId: "team-5",
    competitionId: "comp-1",
    scheduledAt: new Date(tomorrow.getTime() + 3 * 60 * 60 * 1000),
    closedAt: new Date(tomorrow.getTime() + 2.5 * 60 * 60 * 1000),
    status: "SCHEDULED",
    venue: "Arena Allianz Parque",
    pointsMultiplier: 1.0,
    createdAt: now,
    homeTeam: mockTeams[2],
    awayTeam: mockTeams[4],
    competition: mockCompetitions[0],
  },
  {
    id: "match-4",
    homeTeamId: "team-9",
    awayTeamId: "team-10",
    competitionId: "comp-2",
    scheduledAt: new Date(tomorrow.getTime() + 5 * 60 * 60 * 1000),
    closedAt: new Date(tomorrow.getTime() + 4.5 * 60 * 60 * 1000),
    status: "SCHEDULED",
    venue: "Estádio Olímpico de Montjuïc",
    pointsMultiplier: 1.5,
    createdAt: now,
    homeTeam: mockTeams[8],
    awayTeam: mockTeams[9],
    competition: mockCompetitions[1],
  },
  {
    id: "match-5",
    homeTeamId: "team-4",
    awayTeamId: "team-6",
    competitionId: "comp-1",
    scheduledAt: new Date(dayAfter.getTime() + 2 * 60 * 60 * 1000),
    closedAt: new Date(dayAfter.getTime() + 1.5 * 60 * 60 * 1000),
    status: "SCHEDULED",
    venue: "Vila Belmiro",
    pointsMultiplier: 1.0,
    createdAt: now,
    homeTeam: mockTeams[3],
    awayTeam: mockTeams[5],
    competition: mockCompetitions[0],
  },
  {
    id: "match-6",
    homeTeamId: "team-1",
    awayTeamId: "team-3",
    competitionId: "comp-1",
    scheduledAt: new Date(yesterday.getTime()),
    closedAt: new Date(yesterday.getTime() - 30 * 60 * 1000),
    status: "FINISHED",
    homeScore: 2,
    awayScore: 1,
    venue: "Estádio Maracanã",
    pointsMultiplier: 1.0,
    createdAt: yesterday,
    homeTeam: mockTeams[0],
    awayTeam: mockTeams[2],
    competition: mockCompetitions[0],
  },
  {
    id: "match-7",
    homeTeamId: "team-7",
    awayTeamId: "team-9",
    competitionId: "comp-2",
    scheduledAt: new Date(yesterday.getTime() - 2 * 60 * 60 * 1000),
    closedAt: new Date(yesterday.getTime() - 2.5 * 60 * 60 * 1000),
    status: "FINISHED",
    homeScore: 3,
    awayScore: 1,
    venue: "Etihad Stadium",
    pointsMultiplier: 1.5,
    createdAt: yesterday,
    homeTeam: mockTeams[6],
    awayTeam: mockTeams[8],
    competition: mockCompetitions[1],
  },
];

export const mockUsers: Omit<User, "updatedAt">[] = [
  {
    id: "user-1",
    email: "carlos.lima@email.com",
    name: "Carlos Lima",
    role: "USER",
    status: "ACTIVE",
    totalPoints: 1840,
    weeklyPoints: 245,
    monthlyPoints: 820,
    globalRank: 14,
    favoriteTeam: "Flamengo",
    createdAt: new Date("2024-01-15"),
    lastLoginAt: new Date(),
  },
  {
    id: "user-2",
    email: "julia.santos@email.com",
    name: "Julia Santos",
    role: "USER",
    status: "ACTIVE",
    totalPoints: 2120,
    weeklyPoints: 312,
    monthlyPoints: 950,
    globalRank: 8,
    favoriteTeam: "Palmeiras",
    createdAt: new Date("2024-02-20"),
    lastLoginAt: new Date(),
  },
  {
    id: "user-3",
    email: "rafael.costa@email.com",
    name: "Rafael Costa",
    role: "USER",
    status: "ACTIVE",
    totalPoints: 2450,
    weeklyPoints: 380,
    monthlyPoints: 1100,
    globalRank: 2,
    favoriteTeam: "Corinthians",
    createdAt: new Date("2024-01-05"),
    lastLoginAt: new Date(),
  },
  {
    id: "user-4",
    email: "ana.ferreira@email.com",
    name: "Ana Ferreira",
    role: "USER",
    status: "ACTIVE",
    totalPoints: 1650,
    weeklyPoints: 198,
    monthlyPoints: 720,
    globalRank: 21,
    favoriteTeam: "Santos",
    createdAt: new Date("2024-03-10"),
    lastLoginAt: new Date(),
  },
  {
    id: "user-5",
    email: "pedro.oliveira@email.com",
    name: "Pedro Oliveira",
    role: "USER",
    status: "ACTIVE",
    totalPoints: 3100,
    weeklyPoints: 420,
    monthlyPoints: 1350,
    globalRank: 1,
    favoriteTeam: "Grêmio",
    createdAt: new Date("2023-12-01"),
    lastLoginAt: new Date(),
  },
  {
    id: "user-test",
    email: "user@test.com",
    name: "Usuário Teste",
    role: "USER",
    status: "ACTIVE",
    totalPoints: 500,
    weeklyPoints: 80,
    monthlyPoints: 250,
    globalRank: 150,
    favoriteTeam: "Flamengo",
    createdAt: new Date("2024-06-01"),
    lastLoginAt: new Date(),
  },
  {
    id: "reseller-test",
    email: "reseller@test.com",
    name: "Rafael Silva",
    role: "RESELLER",
    status: "ACTIVE",
    totalPoints: 0,
    weeklyPoints: 0,
    monthlyPoints: 0,
    globalRank: null,
    favoriteTeam: null,
    createdAt: new Date("2024-05-01"),
    lastLoginAt: new Date(),
  },
];

export const mockBoloes: Bolao[] = [
  {
    id: "bolao-1",
    name: "Amigos do Trampo",
    description: "Bolão do pessoal do trabalho",
    inviteCode: "AMIG42",
    createdById: "user-1",
    isPublic: false,
    status: "ACTIVE",
    maxMembers: 20,
    createdAt: new Date("2024-06-01"),
    _count: { members: 15 },
  },
  {
    id: "bolao-2",
    name: "Família Flamenguista",
    description: "Só nação ruubro-negra",
    inviteCode: "MENG81",
    createdById: "user-1",
    isPublic: false,
    status: "ACTIVE",
    createdAt: new Date("2024-05-15"),
    _count: { members: 8 },
  },
  {
    id: "bolao-3",
    name: "Copa dos Amigos",
    description: "Bolão público geral",
    inviteCode: "COPA33",
    createdById: "user-3",
    isPublic: true,
    status: "ACTIVE",
    createdAt: new Date("2024-04-10"),
    _count: { members: 45 },
  },
];

export const mockPrizes: Prize[] = [
  {
    id: "prize-1",
    name: "Bola Oficial",
    description: "A mesma bola usada nas finais europeias.",
    imageUrl: null,
    pointsCost: 1500,
    stock: 10,
    isActive: true,
  },
  {
    id: "prize-2",
    name: "Camisa Oficial",
    description: "Manto sagrado do seu time do coração.",
    imageUrl: null,
    pointsCost: 2500,
    stock: 20,
    isActive: true,
  },
  {
    id: "prize-3",
    name: "Chuteira Pro",
    description: "Alta performance para seus jogos.",
    imageUrl: null,
    pointsCost: 5000,
    stock: 5,
    isActive: true,
  },
  {
    id: "prize-4",
    name: "Ingresso VIP",
    description: "Experiência única direto do camarote.",
    imageUrl: null,
    pointsCost: 8000,
    stock: 3,
    isActive: true,
  },
];

export const mockTenant: Tenant = {
  id: "tenant-1",
  slug: "bolaofc",
  platformName: "BolãoFC",
  tagline: "O melhor bolão do futebol brasileiro",
  primaryColor: "#FF6B00",
  secondaryColor: "#FFCA28",
  bgColor: "#0B1120",
  logoUrl: null,
  faviconUrl: null,
  customDomain: "bolaofc.com.br",
  subdomain: "bolaofc",
  plan: "PRO",
  planStatus: "ACTIVE",
  planExpiresAt: new Date("2025-12-31"),
  maxUsers: 10000,
  ownerId: "reseller-test",
  createdAt: new Date("2024-05-01"),
  updatedAt: new Date(),
};
